server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book_service?usaTimezone=true&serverTimezone=UTC
      username: root
      password:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
       fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    user: root
    password: 
